### ISSUE TITLE
csv파일 view 문제

### ISSUE THREAD

**Issue by lawliet62** [junggyo1020/HYU_CSE_Final#17]
csv파일들을 IDE에서 편하게 보기 위해 csv 파일을 xlsx로 변환하는 모듈을 만들었는데, 알고 보니 csv 파일 열고 우클릭하고 테이블 편집 버튼을 누르면 테이블 형식으로 볼 수 있음. 파일 형식 변환 모듈을 삭제해야 될지 가벼운 논의가 필요할 듯.

**Comment by junggyo1020** [comment]
삭제하는 것으로 결정하겠습니다!
