### ISSUE TITLE
[BUG] WMT 데이터셋 평가 시 reference와 hypotheses 설정 오류

### ISSUE THREAD

**Issue by lawliet62** [junggyo1020/HYU_CSE_Final#18]
### 문제 설명
WMT 데이터셋을 사용하여 기계 번역(MT) 모델을 평가하는 과정에서 `reference`와 `hypotheses` 설정이 올바르지 않아 평가 결과가 잘못될 가능성이 있습니다.

현재 설정은 다음과 같습니다:
- **reference**: 독일어를 번역한 영어 문장(참조 번역).
- **hypotheses**: 원문의 영어 문장(소스 텍스트).

이 설정은 평가 지표(BLEU, ROUGE 등)가 기계 번역 모델의 성능을 제대로 평가하지 못하게 만듭니다. `hypotheses`는 원문이 아니라 **기계 번역 시스템이 생성한 번역 결과**여야 하기 때문입니다.

---

### 기대 동작
기계 번역 모델의 올바른 평가를 위해 다음과 같은 설정이 필요합니다:
- **reference**: 독일어 원문을 번역한 인간 번역(참조 번역).
- **hypotheses**: 기계 번역 시스템이 생성한 영어 문장(번역 결과).

---

### 재현 방법
1. `reference`에 독일어를 번역한 영어 문장을 설정합니다.
2. `hypotheses`에 원문의 영어 문장을 설정합니다.

---

### 제안된 해결 방법
문서화 또는 가이드를 업데이트하여 `reference`와 `hypotheses`를 올바르게 설정하는 방법을 명확히 설명해 주세요. 
다음과 같은 기준이 필요합니다:
- `reference`: 독일어 원문을 번역한 인간 번역.
- `hypotheses`: 기계 번역 시스템이 생성한 영어 번역 결과.

---

### 추가 설명
현재 설정은 `reference`와 `hypotheses`가 비교 기준으로 일치하지 않아 평가 결과의 신뢰성을 떨어뜨릴 수 있습니다. 이슈 해결을 통해 기계 번역 모델의 성능 평가가 더욱 명확해질 것입니다.

**Comment by junggyo1020** [comment]
해결했습니다. closed 된 이슈는 한번에 묶어서 PR올리겠습니다.
